---
title: "Untitled"
author: "지후"
date: "2022-10-05"
output: html_document
---

```{r}
install.packages("readxl")
library(readxl)

install.packages("tidyverse")
install.packages("tidytext")
install.packages("kableExtra")

library(tidyverse)
library(tidytext)
library(kableExtra)


```
```{r}

list.files("data/.")

list.files("data/knusenti/KnuSentiLex-master/")

senti_name_v <- list.files("data/knusenti/KnuSentiLex-master/.")[9]

senti_name_v

read_lines(str_c("data/knusenti/KnuSentiLex-master/", senti_name_v)) %>% head(10)

read_lines(str_c("data/knusenti/KnuSentiLex-master/", senti_name_v)) %>% 
  head(10) %>% str_extract("\t|\n| ")

read_tsv(str_c("data/knusenti/KnuSentiLex-master/", senti_name_v)) %>% head(10)
read_tsv(str_c("data/knusenti/KnuSentiLex-master/", senti_name_v), col_names = F) %>% head(10)

senti_dic_df <- read_tsv(str_c("data/knusenti/KnuSentiLex-master/", senti_name_v), col_names = F)

glimpse(senti_dic_df)

senti_dic_df[1-5, ]

senti_dic_df <- senti_dic_df %>% rename(word = X1, sScore = X2)
glimpse(senti_dic_df)

```



```{r}

text.v <- read_excel("마사회제목.xlsx")

text_df <- text.v

text_df %>% unnest_tokens(output = word, input = text)

text_tk <- text_df %>% 
  unnest_tokens(output = word,
                input = text) %>% 
  count(word, sort = T)

text_tk

text_tk %>%
  filter(n >= 15, n < 31) %>% 
  mutate(word = reorder(word, n)) %>% 
  ggplot(aes(word, n)) +
  geom_col() +
  coord_flip()



text.c <- read_excel("수자원제목.xlsx")

text_df1 <- text.c

text_df1 %>% unnest_tokens(output = word, input = 제목)

text_tk1 <- text_df1 %>% 
  unnest_tokens(output = word,
                input = 제목) %>% 
  count(word, sort = T)

text_tk1

text_tk1 %>%
  filter(n >= 15, n < 31) %>% 
  mutate(word = reorder(word, n)) %>% 
  ggplot(aes(word, n)) +
  geom_col() +
  coord_flip()




```

