---
title: "지후"
format: html
editor: visual
---

```{r}
#| echo: false
#| include: false


install.packages("readxl")
library(readxl)

install.packages("tidyverse")
install.packages("tidytext")
install.packages("kableExtra")

library(tidyverse)
library(tidytext)
library(kableExtra)

install.packages("wordcloud")
library(wordcloud)
install.packages("ggplot2")
library(ggplot2)

```

```{r}
#| echo: false
#| include: false

list.files("data/.")

list.files("data/knusenti/KnuSentiLex-master/")

senti_name_v <- list.files("data/knusenti/KnuSentiLex-master/.")[9]

senti_name_v

read_lines(str_c("data/knusenti/KnuSentiLex-master/", senti_name_v)) %>% head(10)

read_lines(str_c("data/knusenti/KnuSentiLex-master/", senti_name_v)) %>% 
  head(10) %>% str_extract("\t|\n| ")

read_tsv(str_c("data/knusenti/KnuSentiLex-master/", senti_name_v)) %>% head(10)
read_tsv(str_c("data/knusenti/KnuSentiLex-master/", senti_name_v), col_names = F) %>% head(10)

senti_dic_df <- read_tsv(str_c("data/knusenti/KnuSentiLex-master/", senti_name_v), col_names = F)

glimpse(senti_dic_df)

senti_dic_df[1-5, ]

senti_dic_df <- senti_dic_df %>% rename(word = X1, sScore = X2)
glimpse(senti_dic_df)


```

## 마사회, 수자원 제목 정리

```{r}

text.3 <- read_excel("마사회제목.xlsx")


text.3 %>% 
  unnest_tokens(output = word,
                input = text) %>% 
  count(word, sort = T)

tibble(text.3) %>% 
  unnest_tokens(output = word, input = text,
                token = "words") %>% 
 inner_join(senti_dic_df)


text.3 %>% 
  unnest_tokens(word, text) %>% 
  inner_join(senti_dic_df) %>% 
  count(word, sScore, sort = T) %>% 
  filter(str_length(word) > 1) %>% 
  mutate(word = reorder(word, n)) %>% 
  slice_head(n = 20) -> text.4


text.3 %>% 
  unnest_tokens(word, text) %>% 
  left_join(senti_dic_df) %>% 
  mutate(sScore = ifelse(sScore >= 1, "긍정",
                         ifelse(sScore <= -1, "부정", "중립"))) %>% 
  count(sScore)

text.r %>% 
  ggplot() + geom_col(aes(n, word), show.legend = F)

text.3 %>% 
  unnest_tokens(word, text) %>% 
  inner_join(senti_dic_df) %>% 
  mutate(emotion = ifelse(sScore > 0, "긍정", ifelse(sScore < 0, "부정", "중립"))) %>% 
  filter(emotion != "중립") %>% 
  count(word, emotion, sort = T) %>% 
  filter(str_length(word) > 1) %>% 
  reshape2::acast(word ~ emotion, value.var = "n", fill = 0) %>% 
  comparison.cloud(colors = c("blue", "red"), max.words = 50)



  
text.1 <- read_excel("수자원제목.xlsx")


text.1 %>% 
  unnest_tokens(output = word,
                input = text) %>% 
  count(word, sort = T)

tibble(text.1) %>% 
  unnest_tokens(output = word, input = text,
                token = "words") %>% 
 inner_join(senti_dic_df)


text.1 %>% 
  unnest_tokens(word, text) %>% 
  inner_join(senti_dic_df) %>% 
  count(word, sScore, sort = T) %>% 
  filter(str_length(word) > 1) %>% 
  mutate(word = reorder(word, n)) %>% 
  slice_head(n = 20) -> text.2



text.1 %>% 
  unnest_tokens(word, text) %>% 
  left_join(senti_dic_df) %>% 
  mutate(sScore = ifelse(sScore >= 1, "긍정",
                         ifelse(sScore <= -1, "부정", "중립"))) %>% 
  count(sScore)

text.2 %>% 
  ggplot() + geom_col(aes(n, word), show.legend = F)

text.1 %>% 
  unnest_tokens(word, text) %>% 
  inner_join(senti_dic_df) %>% 
  mutate(emotion = ifelse(sScore > 0, "긍정", ifelse(sScore < 0, "부정", "중립"))) %>% 
  filter(emotion != "중립") %>% 
  count(word, emotion, sort = T) %>% 
  filter(str_length(word) > 1) %>% 
  reshape2::acast(word ~ emotion, value.var = "n", fill = 0) %>% 
  comparison.cloud(colors = c("blue", "red"), max.words = 50)

```

## 마사회 기사 키워드 정리

```{r}

#| echo: false
#| include: false

text.v <- read_excel("마사회키워드.xlsx")


text.v %>% 
  unnest_tokens(word, text) %>% 
  left_join(senti_dic_df) %>% 
  mutate(sScore = ifelse(sScore >= 1, "긍정",
                         ifelse(sScore <= -1, "부정", "중립"))) %>% 
  count(sScore)

text.v %>% 
  unnest_tokens(word, text) %>% 
  inner_join(senti_dic_df) %>% 
  mutate(emotion = ifelse(sScore > 0, "긍정", ifelse(sScore < 0, "부정", "중립"))) %>% 
  filter(emotion != "중립") %>% 
  count(word, emotion, sort = T) %>% 
  filter(str_length(word) > 1) %>% 
  reshape2::acast(word ~ emotion, value.var = "n", fill = 0) %>% 
  comparison.cloud(colors = c("blue", "red"), max.words = 50)


text.r %>% 
  ggplot() + geom_col(aes(n, word), show.legend = F)

text.v
```

```{r}

text.q <- read_excel("수자원키워드.xlsx")


text.q %>% 
  unnest_tokens(word, text) %>% 
  left_join(senti_dic_df) %>% 
  mutate(sScore = ifelse(sScore >= 1, "긍정",
                         ifelse(sScore <= -1, "부정", "중립"))) %>% 
  count(sScore)

text.w %>% 
  ggplot() + geom_col(aes(n, word), show.legend = F)

text.q %>% 
  unnest_tokens(word, text) %>% 
  inner_join(senti_dic_df) %>% 
  mutate(emotion = ifelse(sScore > 0, "긍정", ifelse(sScore < 0, "부정", "중립"))) %>% 
  filter(emotion != "중립") %>% 
  count(word, emotion, sort = T) %>% 
  filter(str_length(word) > 1) %>% 
  reshape2::acast(word ~ emotion, value.var = "n", fill = 0) %>% 
  comparison.cloud(colors = c("blue", "red"), max.words = 50)

  
```
```{r}
data.frame <- read_excel("수자원,마사회키워드.xlsx")

text.0 <- data.frame

text.0 %>%
unnest_tokens(main, text , token = "word") %>% 
  mutate(main = row_number()) %>% 
  unnest_tokens(word, main) %>% 
  inner_join(senti_dic_df) %>% 
  mutate(emotion = ifelse(sScore > 0, "긍정", 
                          ifelse(sScore < 0, "부정", "중립"))) %>% 
  count(text, index = main)


```

