---
title: "수자원공사, 마사회 기사 비교분석"
format: html
author: 언론홍보학과 2019102107 김지후
title-block-style: default
title-block-banner: "#6E6E6E"
date: 2022-10-12
code-fold: true
code-tools: true
---

## 빅카인즈에서 데이터셋을 추출해 두 공사간 비교분석을 실시함

### 1. 필요 패키지 설치

### 2. 각 공사 키워드별 상위단어 분석

### 3. 각 공사 키워드별 긍정, 부정단어 분석

### 필요 패키지 설치

```{r}
#| warning: false


package_list <- c("tidyverse", "tidytext", "readxl", "kableExtra", 
                  "multilinguer", "RcppMeCab", "KoNLP", "lubridate", 
                  "tidylo", "stm", "reshape2", "dplyr", "ggplot2", 
                  "stringr", "rvest", "wordcloud", "tm", "VennDiagram", "gt",repos = "http://cran.us.r-project.org")
 

library(tidylo)
library(tidyverse)
library(tidytext)
library(kableExtra)
library(wordcloud)

list.files("data/.")

list.files("data/knusenti/KnuSentiLex-master/")

senti_name_v <- list.files("data/knusenti/KnuSentiLex-master/.")[9]

senti_name_v

read_lines(str_c("data/knusenti/KnuSentiLex-master/", senti_name_v)) %>% head(10)

read_lines(str_c("data/knusenti/KnuSentiLex-master/", senti_name_v)) %>% 
  head(10) %>% str_extract("\t|\n| ")

read_tsv(str_c("data/knusenti/KnuSentiLex-master/", senti_name_v)) %>% head(10)
read_tsv(str_c("data/knusenti/KnuSentiLex-master/", senti_name_v), col_names = F) %>% head(10)

senti_dic_df <- read_tsv(str_c("data/knusenti/KnuSentiLex-master/", senti_name_v), col_names = F)

glimpse(senti_dic_df)

senti_dic_df[1-5, ]

senti_dic_df <- senti_dic_df %>% rename(word = X1, sScore = X2)
glimpse(senti_dic_df)
```

## 키워드 주요 단어 분석

```{r}
text.v <- read_excel("마사회키워드.xlsx")
text.z <- read_excel("수자원키워드.xlsx")

text.v_df <-  text.v %>% 
  unnest_tokens(word, text, token = "words") %>%
  mutate(ID = factor(row_number())) %>% 
  inner_join(senti_dic_df) %>% 
  count(word, sScore, sort = T) %>% 
  filter(str_length(word) > 1) %>% 
  mutate(word = reorder(word, n)) %>% 
  slice_head(n = 20)

text.v_df %>% 
  ggplot() + geom_col(aes(n, word, fill = sScore), show.legend = F) +
    labs(title = "마사회 키워드 감정빈도 분석")

text.z_df <- text.z %>% 
  unnest_tokens(word, text, token = "words") %>% 
  mutate(ID = factor(row_number())) %>% 
  inner_join(senti_dic_df) %>% 
  count(word, sScore, sort = T) %>% 
  filter(str_length(word) > 1) %>% 
  filter(!word %in% c("대상")) %>% 
  mutate(word = reorder(word, n)) %>% 
  slice_head(n = 20)


text.z_df %>% 
  ggplot() + geom_col(aes(n, word, fill = sScore), show.legend = F) +
    labs(title = "수자원 공사 키워드 분석")


text.v %>% 
  unnest_tokens(word, text) %>% 
  inner_join(senti_dic_df) %>% 
  mutate(emotion = ifelse(sScore > 0, "긍정", ifelse(sScore < 0, "부정", "중립"))) %>% 
  filter(emotion != "중립") %>% 
  count(word, emotion, sort = T) %>% 
  filter(str_length(word) > 1) %>% 
  reshape2::acast(word ~ emotion, value.var = "n", fill = 0) %>% 
  comparison.cloud(colors = c("blue", "red"), max.words = 50)

text.z %>% 
  unnest_tokens(word, text) %>% 
  inner_join(senti_dic_df) %>% 
  mutate(emotion = ifelse(sScore > 0, "긍정", ifelse(sScore < 0, "부정", "중립"))) %>% 
  filter(emotion != "중립") %>% 
  count(word, emotion, sort = T) %>% 
  filter(str_length(word) > 1) %>% 
  reshape2::acast(word ~ emotion, value.var = "n", fill = 0) %>% 
  comparison.cloud(colors = c("blue", "red"), max.words = 50)



```

## 공사간 긍정, 부정어 분석

```{r}

text.z %>% 
  unnest_tokens(word, text) %>% 
  left_join(senti_dic_df) %>% 
  mutate(sScore = ifelse(sScore >= 1, "긍정",
                         ifelse(sScore <= -1, "부정", "중립"))) %>% 
  count(sScore) %>%
   labs(title = "수자원공사 긍부정")


text.v %>% 
  unnest_tokens(word, text) %>% 
  left_join(senti_dic_df) %>% 
  mutate(sScore = ifelse(sScore >= 1, "긍정",
                         ifelse(sScore <= -1, "부정", "중립"))) %>% 
  count(sScore) %>%
   labs(title = "마사회 긍부정")

text.z %>%   
  unnest_tokens(word, text, token = "words") %>% 
  inner_join(senti_dic_df) %>% 
  mutate(emotion = ifelse(sScore > 0, "긍정", ifelse(sScore < 0, "부정", "중립"))) %>%
  mutate(label = ifelse(sScore > 0, "1", ifelse(sScore < 0, "0", "2"))) %>%
  filter(label != "중립") %>%
  count(word, emotion, label, sort = T) %>%
  filter(str_length(word) > 1) %>%
  group_by(label = ifelse(label > 0, "긍정", "부정")) %>%
  slice_head(n = 15) %>%
  ggplot(aes(x = n,
             y = reorder(word, n), fill = label)) +
  geom_col(show.legend = F) +
  facet_wrap(~label, scale = "free") +
  labs(title = "수자원공사 긍정어 부정어")

text.v %>%   
  unnest_tokens(word, text, token = "words") %>% 
  inner_join(senti_dic_df) %>% 
  mutate(emotion = ifelse(sScore > 0, "긍정", ifelse(sScore < 0, "부정", "중립"))) %>%
  mutate(label = ifelse(sScore > 0, "1", ifelse(sScore < 0, "0", "2"))) %>%
  filter(label != "중립") %>%
  count(word, emotion, label, sort = T) %>%
  filter(str_length(word) > 1) %>%
  group_by(label = ifelse(label > 0, "긍정", "부정")) %>%
  slice_head(n = 15) %>%
  ggplot(aes(x = n,
             y = reorder(word, n), fill = label)) +
  geom_col(show.legend = F) +
  facet_wrap(~label, scale = "free") +
  labs(title = "마사회 긍정어 부정어")



```

```{r}
pkg_v <- c("tidyverse", "tidytext", "tidylo")
lapply(pkg_v, require, ch = T)

text.v_df <- text.v %>% 
  mutate(text = str_remove_all(text, "[^(\\w+|\\s)]")) %>%  
  unnest_tokens(word, text, token = "words", drop = F)

text.v_df %>% 
  filter(!word %in% c("한국마사회", "경마", "영천경마공원", "기자")) %>% 
  filter(str_detect(word, "[:alpha:]+"))





```

